# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test

on:
  push:
    tags: '**'
  pull_request:
    branches: [ main ]

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get version
        id: get_version
        run: |
          # Use awk to find the version line and extract the string inside quotes
          grep "^version =" pyproject.toml | awk -F'"' '{print $2}'

      - name: zip examples
        run: |
          echo "Zipping examples"
          zip -r examples.zip examples/
          tar czf examples.tgz examples/

      - name: upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: examples.zip
          path: examples${{ steps.get_version.outputs.stdout }}.zip
          # retention-days: 14

      - name: upload tgz artifact
        uses: actions/upload-artifact@v4
        with:
          name: examples.tgz
          path: examples${{ steps.get_version.outputs.stdout }}.tgz
          # retention-days: 14
